-- =============================================================================
-- ACM v11.0.0 - DROP DEPRECATED TABLES
-- =============================================================================
-- These tables are no longer generated by the ACM pipeline.
-- They were removed as part of the v11 cleanup to reduce bloat.
-- Run this script to clean up the database.
-- =============================================================================

-- DEPRECATED ANALYTICS TABLES (were generated by finalize_outputs)
DROP TABLE IF EXISTS ACM_AlertAge;
DROP TABLE IF EXISTS ACM_CalibrationSummary;
DROP TABLE IF EXISTS ACM_ContributionCurrent;
DROP TABLE IF EXISTS ACM_ContributionTimeline;
DROP TABLE IF EXISTS ACM_DailyFusedProfile;
DROP TABLE IF EXISTS ACM_DefectSummary;
DROP TABLE IF EXISTS ACM_DefectSummary_Latest;
DROP TABLE IF EXISTS ACM_DefectTimeline;
DROP TABLE IF EXISTS ACM_DetectorCorrelation;
DROP TABLE IF EXISTS ACM_DriftEvents;
DROP TABLE IF EXISTS ACM_DriftSeries;
DROP TABLE IF EXISTS ACM_EpisodeDiagnostics;
DROP TABLE IF EXISTS ACM_EpisodeMetrics;
DROP TABLE IF EXISTS ACM_EpisodesQC;
DROP TABLE IF EXISTS ACM_FusionQualityReport;
DROP TABLE IF EXISTS ACM_HealthDistributionOverTime;
DROP TABLE IF EXISTS ACM_HealthHistogram;
DROP TABLE IF EXISTS ACM_HealthZoneByPeriod;
DROP TABLE IF EXISTS ACM_OMRContributionsLong;
DROP TABLE IF EXISTS ACM_OMRTimeline;
DROP TABLE IF EXISTS ACM_RegimeDwellStats;
DROP TABLE IF EXISTS ACM_RegimeOccupancy;
DROP TABLE IF EXISTS ACM_RegimeStability;
DROP TABLE IF EXISTS ACM_RegimeStats;
DROP TABLE IF EXISTS ACM_RegimeTransitions;
DROP TABLE IF EXISTS ACM_SensorAnomalyByPeriod;
DROP TABLE IF EXISTS ACM_SensorHotspotTimeline;
DROP TABLE IF EXISTS ACM_SensorNormalized_TS;
DROP TABLE IF EXISTS ACM_SensorRanking;
DROP TABLE IF EXISTS ACM_SinceWhen;
DROP TABLE IF EXISTS ACM_ThresholdCrossings;
DROP TABLE IF EXISTS ACM_ThresholdCrossings_Latest;

-- DEPRECATED FORECAST TABLES (replaced by consolidated tables)
DROP TABLE IF EXISTS ACM_DetectorForecast_TS;
DROP TABLE IF EXISTS ACM_FailureHazard_TS;
DROP TABLE IF EXISTS ACM_HealthForecast_Continuous;

-- DEPRECATED PCA TABLES (model info now in ModelRegistry)
DROP TABLE IF EXISTS ACM_PCA_Loadings;
DROP TABLE IF EXISTS ACM_PCA_Metrics;
DROP TABLE IF EXISTS ACM_PCA_Models;

-- DEPRECATED OMR TABLES (consolidated into main scoring)
DROP TABLE IF EXISTS ACM_OMR_Diagnostics;
DROP TABLE IF EXISTS ACM_OMR_SensorContributions;

-- DEPRECATED RUN TABLES (consolidated into ACM_Runs)
DROP TABLE IF EXISTS ACM_Run_Stats;

-- DEPRECATED REGIME TABLES
DROP TABLE IF EXISTS ACM_Regime_Episodes;
DROP TABLE IF EXISTS ACM_RegimeState;

-- DEPRECATED ANOMALY TABLE (replaced by ACM_Episodes)
DROP TABLE IF EXISTS ACM_Anomaly_Events;

-- DEPRECATED LATEST VIEWS (can be derived with ROW_NUMBER())
DROP TABLE IF EXISTS ACM_Episodes_Latest;
DROP TABLE IF EXISTS ACM_HealthTimeline_Latest;
DROP TABLE IF EXISTS ACM_RegimeTimeline_Latest;
DROP TABLE IF EXISTS ACM_Scores_Wide_Latest;
DROP TABLE IF EXISTS ACM_SensorHotspots_Latest;

-- DEPRECATED STATE/CONFIG TABLES
DROP TABLE IF EXISTS ACM_ForecastState;
DROP TABLE IF EXISTS ACM_LatestThresholds;
DROP TABLE IF EXISTS ACM_ThresholdMetadata;
DROP TABLE IF EXISTS ACM_RefitRequests;
DROP TABLE IF EXISTS ACM_FeatureDropLog;
DROP TABLE IF EXISTS ACM_ResourceMetrics;
DROP TABLE IF EXISTS ACM_RUL_LearningState;

-- DEPRECATED LONG FORMAT (Wide is primary)
DROP TABLE IF EXISTS ACM_Scores_Long;

PRINT 'Dropped 54 deprecated tables';
GO
