"""Check sensor names in OMR contributions table."""
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from core.sql_client import SQLClient
from utils.config_dict import ConfigDict

cfg = ConfigDict.from_csv("configs/config_table.csv", equip_id=1)
client = SQLClient(cfg)
client.connect()
cursor = client.cursor()

print("\nAnalyzing OMR SensorNames...")
print("=" * 80)

# Get all unique sensor names
cursor.execute("SELECT DISTINCT SensorName FROM ACM_OMRContributionsLong ORDER BY SensorName")
rows = cursor.fetchall()
all_sensors = [row[0] for row in rows]

print(f"\nTotal unique sensors: {len(all_sensors)}")
print("\nSample sensor names (first 30):")
for i, sensor in enumerate(all_sensors[:30], 1):
    print(f"  {i}. {sensor}")

if len(all_sensors) > 30:
    print(f"\n... and {len(all_sensors) - 30} more")

# Check for patterns
raw_sensors = [s for s in all_sensors if not any(x in s for x in ['_mean', '_std', '_max', '_min', '_energy', '_kurt', '_mad', '_skew', '_q'])]
stat_sensors = [s for s in all_sensors if any(x in s for x in ['_mean', '_std', '_max', '_min', '_energy', '_kurt', '_mad', '_skew', '_q'])]

print("\n" + "=" * 80)
print(f"\nBreakdown:")
print(f"  Raw sensor features: {len(raw_sensors)}")
print(f"  Statistical features: {len(stat_sensors)}")
print(f"  Total: {len(all_sensors)}")

print("\n" + "=" * 80)
print("\nExample raw sensor (if any):")
if raw_sensors:
    for sensor in raw_sensors[:5]:
        print(f"  - {sensor}")
else:
    print("  (none found)")

print("\nExample statistical features:")
for sensor in stat_sensors[:10]:
    print(f"  - {sensor}")

print("\n" + "=" * 80)
print("\nConclusion:")
print("  These are FAST FEATURES generated by core/fast_features.py")
print("  Each raw sensor is transformed into multiple statistical features:")
print("    - mean, std, max, min (basic stats)")
print("    - energy_1, energy_2 (energy features)")
print("    - kurt, skew (distribution shape)")
print("    - mad (median absolute deviation)")
print("    - q25, q75 (quartiles)")
print("\n  This is CORRECT - OMR operates on fast features, not raw sensors.")
print("  Dashboard should aggregate or filter these appropriately.")

cursor.close()
client.close()
